#!/bin/bash

if [ $1 = "enable" ]
then

    echo "enabling xdebug.so"

    ./cmd mv /docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

fi

if [ $1 = "disable" ]
then

    echo "disabling xdebug.so"

    ./cmd mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /docker-php-ext-xdebug.ini

fi

echo "reload php-fpm"
docker-compose restart php-fpm-local

echo "done"
